"""Deterministic CI operations for Phase 8 (CI automation).

Handles: PR creation, check-run fetching, pytorch-bot comment
fetch/parse. Called by ci_ops.py — no AI logic in this module.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

from state import CICheckRun, CIBotHints, CIFailure


# ── PR creation ─────────────────────────────────────────────────────


def create_branch(file_path: str) -> str:
    """Create and checkout a new branch for the PR.

    Returns the branch name.
    """
    file_name = Path(file_path).stem
    branch = f"refactor-{file_name}"
    _run_git("checkout", "-b", branch)
    return branch


def commit_changes(file_path: str, branch: str) -> str:
    """Stage and commit all changes. Returns the commit SHA."""
    # Stage the refactored test file and any external reference updates
    _run_git("add", file_path)

    # Also stage dynamo_skips / dynamo_expected_failures renames if any
    dynamo_dirs = ["test/dynamo_skips", "test/dynamo_expected_failures"]
    for d in dynamo_dirs:
        if Path(d).exists():
            _run_git("add", d)

    # Stage common_methods_invocations.py if changed
    cmi = "torch/testing/_internal/common_methods_invocations.py"
    if Path(cmi).exists():
        _run_git("add", cmi)

    _run_git(
        "commit",
        "-m",
        f"[refactor] Decouple {Path(file_path).stem} from device-specific APIs\n\n"
        f"Apply test decoupling strategies (S1/S2/S3) to {file_path}.\n"
        f"Generated by pytorch-test-refactoring skill.",
    )
    return _run_git("rev-parse", "HEAD").strip()


def detect_fork_remote() -> str:
    """Detect the fork remote name.

    Checks if 'origin' is a fork (different owner from 'upstream').
    If not, scans all remotes for one with a different owner.
    Raises RuntimeError if no fork remote is found.
    """
    remotes = _run_git("remote").strip().split("\n")

    # Get upstream owner
    upstream_owner = None
    for remote in remotes:
        url = _run_git("remote", "get-url", remote).strip()
        if "upstream" in remote.lower() or "pytorch/pytorch" in url:
            owner_match = re.search(r"github\.com[:/]([^/]+)/", url)
            if owner_match:
                upstream_owner = owner_match.group(1)
                break

    if upstream_owner is None:
        # Assume 'origin' IS upstream
        return "origin"

    # Check if origin is a fork
    if "origin" in remotes:
        origin_url = _run_git("remote", "get-url", "origin").strip()
        origin_match = re.search(r"github\.com[:/]([^/]+)/", origin_url)
        if origin_match and origin_match.group(1) != upstream_owner:
            return "origin"

    # Scan other remotes
    for remote in remotes:
        if remote == "upstream":
            continue
        url = _run_git("remote", "get-url", remote).strip()
        owner_match = re.search(r"github\.com[:/]([^/]+)/", url)
        if owner_match and owner_match.group(1) != upstream_owner:
            return remote

    raise RuntimeError(
        "No fork remote detected. Ensure you have a fork configured as a git remote."
    )


def push_branch(branch: str, fork_remote: str) -> None:
    """Push the branch to the fork remote."""
    _run_gh("push", fork_remote, branch, "--force")


def create_draft_pr(branch: str, fork_remote: str, file_path: str) -> tuple[int, str]:
    """Create a draft PR targeting upstream main.

    Returns (pr_number, pr_url).
    """
    file_name = Path(file_path).stem
    title = f"[WIP] Decouple {file_name} from device-specific APIs"
    body = (
        f"Automated refactoring of `{file_path}` to decouple tests from "
        f"specific hardware accelerators.\n\n"
        f"- **Strategy 1**: Accelerator-unrelated tests (CPU only)\n"
        f"- **Strategy 2**: Accelerator-agnostic tests (device-generic)\n"
        f"- **Strategy 3**: Accelerator-specific tests (single-device)\n\n"
        f"🤖 Generated with [Claude Code](https://claude.com/claude-code)"
    )

    output = _run_gh(
        "pr",
        "create",
        "--draft",
        "--base",
        "main",
        "--head",
        f"{fork_remote}:{branch}",
        "--title",
        title,
        "--body",
        body,
    )
    pr_url = output.strip()
    # Extract PR number from URL: https://github.com/owner/repo/pull/12345
    pr_match = re.search(r"/pull/(\d+)$", pr_url)
    if not pr_match:
        raise RuntimeError(f"Could not parse PR number from URL: {pr_url}")
    return int(pr_match.group(1)), pr_url


# ── CI check-run fetching ───────────────────────────────────────────


def get_check_runs(ref: str) -> list[CICheckRun]:
    """Fetch all check runs for a given git ref (commit SHA).

    Uses `gh api` to call the GitHub Checks API.
    """
    try:
        output = _run_gh(
            "api",
            f"/repos/pytorch/pytorch/commits/{ref}/check-runs",
            "--paginate",
            "-q",
            ".check_runs[] | {name: .name, status: .status, conclusion: .conclusion, html_url: .html_url}",
        )
        if not output.strip():
            return []
        runs = []
        for line in output.strip().split("\n"):
            try:
                data = json.loads(line)
                runs.append(
                    CICheckRun(
                        name=data.get("name", ""),
                        status=data.get("status", ""),
                        conclusion=data.get("conclusion", "") or "",
                        html_url=data.get("html_url", ""),
                    )
                )
            except json.JSONDecodeError:
                continue
        return runs
    except subprocess.CalledProcessError as e:
        import sys

        print(
            f"ci_ops: get_check_runs failed for ref={ref[:12]}: {e}",
            file=sys.stderr,
        )
        return []


def get_check_run_log(check_run_id: int) -> str:
    """Fetch the log output for a specific check run."""
    try:
        return _run_gh(
            "api",
            f"/repos/pytorch/pytorch/check-runs/{check_run_id}/logs",
        )
    except subprocess.CalledProcessError:
        return "(could not fetch logs)"


# ── pytorch-bot comment ─────────────────────────────────────────────


def get_bot_comment(pr_number: int) -> str:
    """Fetch the latest comment from pytorch-bot on the PR.

    Returns the raw markdown body, or empty string if none found.
    """
    # Find the bot user ID first (pytorch-bot or pytorchmergebot)
    for bot_name in ("pytorch-bot", "pytorchmergebot"):
        try:
            output = _run_gh(
                "api",
                f"/repos/pytorch/pytorch/issues/{pr_number}/comments",
                "--jq",
                f'[.[] | select(.user.login=="{bot_name}")] | last | .body',
            )
            if output.strip() and output.strip() != "null":
                return output.strip()
        except subprocess.CalledProcessError:
            continue
    return ""


def parse_bot_comment(raw_comment: str) -> CIBotHints:
    """Best-effort parse of the pytorch-bot comment.

    Extracts hints about flaky checks, unrelated failures, and
    trunk-broken checks. This is NON-BLOCKING: if parsing fails,
    the raw comment is preserved in the hints object.
    """
    hints = CIBotHints(raw_comment=raw_comment)
    if not raw_comment:
        return hints

    # Pattern 1: "flaky" mentions
    flaky_patterns = [
        r'(?:check|workflow|test)\s+"?([^"]+?)"?\s+(?:is|appears|seems)\s+flaky',
        r'(?:flaky|unstable):\s*"?([^"\n]+)"?',
    ]
    for pattern in flaky_patterns:
        for match in re.finditer(pattern, raw_comment, re.IGNORECASE):
            name = match.group(1).strip()
            if name and name not in hints.flaky_checks:
                hints.flaky_checks.append(name)

    # Pattern 2: "unrelated" / "not caused by this PR"
    unrelated_patterns = [
        r'(?:failure|check|workflow)\s+"?([^"]+?)"?\s+(?:is|appears)\s+(?:unrelated|not caused)',
        r'(?:unrelated|not caused by this PR):\s*"?([^"\n]+)"?',
    ]
    for pattern in unrelated_patterns:
        for match in re.finditer(pattern, raw_comment, re.IGNORECASE):
            name = match.group(1).strip()
            if name and name not in hints.unrelated_failures:
                hints.unrelated_failures.append(name)

    # Pattern 3: "broken on trunk"
    trunk_patterns = [
        r'(?:check|workflow|test)\s+"?([^"]+?)?"?\s+(?:is|appears)?\s*(?:broken|failing)\s+on\s+trunk',
        r'(?:broken on trunk|trunk failure):\s*"?([^"\n]+)"?',
    ]
    for pattern in trunk_patterns:
        for match in re.finditer(pattern, raw_comment, re.IGNORECASE):
            name = match.group(1).strip()
            if name and name not in hints.trunk_broken:
                hints.trunk_broken.append(name)

    return hints


# ── CI state classification ─────────────────────────────────────────


def classify_ci_state(
    check_runs: list[CICheckRun],
    bot_hints: CIBotHints,
) -> tuple[str, list[CIFailure]]:
    """Classify the overall CI state.

    Returns (verdict, failures) where verdict is one of:
      - "all_pass": all checks green
      - "all_excused": all failures are excused by bot hints
      - "failures": some failures are not excused, need debugger
      - "pending": some checks still running, OR no check runs fetched
    """
    if not check_runs:
        # Empty check runs list means the API call likely failed (network
        # error, rate limit, etc.).  Assume pending rather than falsely
        # declaring all_pass — a false "done" signal would kill the
        # cron job and abandon CI monitoring.
        return "pending", []

    all_pass = True
    has_pending = False
    failures: list[CIFailure] = []

    for run in check_runs:
        if run.status in ("queued", "in_progress"):
            has_pending = True
            all_pass = False
            continue

        if run.conclusion == "success":
            continue

        if run.conclusion in ("failure", "timed_out", "cancelled"):
            all_pass = False
            bot_label = ""
            if run.name in bot_hints.flaky_checks:
                bot_label = "flaky"
            elif run.name in bot_hints.unrelated_failures:
                bot_label = "unrelated"
            elif run.name in bot_hints.trunk_broken:
                bot_label = "trunk_broken"

            failures.append(
                CIFailure(
                    check_name=run.name,
                    log_excerpt=run.log_snippet,
                    bot_label=bot_label,
                )
            )

    if has_pending:
        return "pending", failures
    if all_pass:
        return "all_pass", []
    if failures and all(f.bot_label for f in failures):
        return "all_excused", failures
    return "failures", failures


# ── PR status management ────────────────────────────────────────────


def mark_pr_ready(pr_number: int) -> None:
    """Mark a draft PR as ready for review."""
    _run_gh("pr", "ready", str(pr_number))


def leave_pr_comment(pr_number: int, body: str) -> None:
    """Leave a comment on the PR."""
    _run_gh("pr", "comment", str(pr_number), "--body", body)


# -- Intermediate JSON files for debugger agent -----------------------


def write_ci_failures_json(
    failures: list[CIFailure],
    workspace: Path,
) -> str:
    """Write CI failures to a JSON file for the debugger to read.

    Returns the file path relative to workspace.
    """
    from datetime import datetime, timezone

    path = workspace / "ci_failures.json"
    data = {
        "total_failed": len(failures),
        "failures": [
            {
                "check_name": f.check_name,
                "log_excerpt": f.log_excerpt,
                "bot_label": f.bot_label,
            }
            for f in failures
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def write_bot_comment_json(
    bot_hints: CIBotHints,
    workspace: Path,
) -> str:
    """Write the bot comment and parsed hints to a JSON file.

    Returns the file path relative to workspace.
    """
    from datetime import datetime, timezone

    path = workspace / "bot_comment.json"
    data = {
        "raw_comment": bot_hints.raw_comment,
        "flaky_checks": bot_hints.flaky_checks,
        "unrelated_failures": bot_hints.unrelated_failures,
        "trunk_broken": bot_hints.trunk_broken,
        "parse_warning": (
            "This parse is automated and may be incomplete. "
            "Always verify against raw_comment."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


# ── Helpers ─────────────────────────────────────────────────────────


def _run_git(*args: str) -> str:
    """Run a git command and return stdout."""
    result = subprocess.run(
        ["git", *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


def _run_gh(*args: str) -> str:
    """Run a gh CLI command and return stdout."""
    result = subprocess.run(
        ["gh", *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout
